Gradle 8 compatibility: replace execResult -> executionResult
piotrmadry/FirebaseTestLab-Android pull request #55
Opened 2023-04-21 15:03 UTC by zbynek

Fixes #54

2023-04-24 06:03 UTC, ThomasRichtsfeld approved these changes

2023-06-11 18:08 UTC, zbynek commented
@piotrmadry will you have time to check this?

2023-06-14 07:24 UTC, ThomasRichtsfeld commented
Would be great if we can get this merged 🙇

2023-06-15 11:21 UTC, tassilo-posegga commented on plugin/src/main/java/com/appunite/firebasetestlabplugin/FirebaseTestLabPlugin.kt
> +                executionResult?.let {
executionResult returns a provider now and is non-nullable.

```
 if (executionResult.get().exitValue != 0) {
        println(standardOutput.toString())
        throw GradleException("exec failed; see output above")
 }
```

2023-06-15 11:22 UTC, tassilo-posegga requested changes
Will not compile as the return type of `executionResult` is now `Provider<ExecResult>` instead of `ExecResult`

2024-04-11 11:30 UTC, zbynek commented
@tassilo-posegga I updated this PR with your suggestion, thanks! As the README meanwhile says, this plugin is no longer maintained. In my fork of this repo I included this PR and https://github.com/piotrmadry/FirebaseTestLab-Android/pull/53 into the `master` branch and initialized a release of a fork of this plugin. If it gets approved by the Gradle team I'll share the new plugin ID here. 

My understanding is that as of Gradle 8 with the latest Android plugin it's possible to [use Firebase devices directly](https://developer.android.com/studio/test/gradle-managed-devices#gmd-ftl), so hopefully this plugin won't be needed for much longer. However, I still think it's useful to have at least one release of this plugin compatible with Gradle 8 to make incremental update of tooling possible.

Closing this PR since repo is no longer maintained.

2024-04-11 11:30 UTC, closed without merging